### ISSUE TITLE
Need help creating an expression

### ISSUE THREAD

**Issue by kshenoy** [tommcdo/vim-express#2]
Hi Tom, I love the idea of this plugin; it fills a huge gap in my workflow I didn't even realize I wanted.

However, I seem to be missing something as the expression I created doesn't seem to work.

I added this statement to my .vimrc

    function! s:InitVimExpress()
      " Description: Creates operators upon startup as the plugin might not have been loaded at this point
      MapExpress gs ':sort'
    endfunction

    augroup BundleInit
      autocmd!
      autocmd VimEnter * call s:InitVimExpress()
    augroup END

and I see the maps getting created upon startup. However, using it as say `gsip` just replaces all the lines with a literal `:sort`

Also, I didn't understand how to use `g=` and `g:`. Let's say I want to create a temporary mapping for `:sort`. 

How would I go about it using `g=`?

Thanks and apologies from my coffee-addled, sleep-deprived brain if I missed something fundamental and/or dumb.

P.S. Could you add examples how you use this to the wiki?

**Comment by tommcdo** [comment]
The mappings for `:MapExpress` are interpreted as a VimScript expression, not as a an Ex command such as `:sort`. You'd need to write an expression using VimScript operators and functions to manipulate the selected text (available as `v:val`) into the desired output.

I'm guessing you're looking for something that would sort the lines matched by the motion supplied to the operator. Something like this (with some tweaking) might do the trick:

    MapExpress gs join(sort(split(v:val, '\n')), '\n')

Take a look at `:help join()`, `:help sort()`, and `:help split()` to work out any details that may need refinement.
